begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|llap
operator|.
name|io
operator|.
name|decode
operator|.
name|orc
operator|.
name|streams
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|llap
operator|.
name|io
operator|.
name|api
operator|.
name|EncodedColumnBatch
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|ColumnVector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|DoubleColumnVector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|io
operator|.
name|orc
operator|.
name|CompressionCodec
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|io
operator|.
name|orc
operator|.
name|InStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|io
operator|.
name|orc
operator|.
name|OrcProto
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|io
operator|.
name|orc
operator|.
name|PositionProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|io
operator|.
name|orc
operator|.
name|RecordReaderImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|io
operator|.
name|orc
operator|.
name|SerializationUtils
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
import|;
end_import

begin_comment
comment|/**  * Float stream reader.  */
end_comment

begin_class
specifier|public
class|class
name|FloatColumnStream
extends|extends
name|BaseColumnStream
block|{
specifier|private
name|InStream
name|dataStream
decl_stmt|;
specifier|private
name|SerializationUtils
name|utils
decl_stmt|;
specifier|public
name|FloatColumnStream
parameter_list|(
name|String
name|file
parameter_list|,
name|int
name|colIx
parameter_list|,
name|EncodedColumnBatch
operator|.
name|StreamBuffer
name|presentStream
parameter_list|,
name|EncodedColumnBatch
operator|.
name|StreamBuffer
name|dataStream
parameter_list|,
name|CompressionCodec
name|codec
parameter_list|,
name|int
name|bufferSize
parameter_list|,
name|OrcProto
operator|.
name|RowIndexEntry
name|rowIndex
parameter_list|)
throws|throws
name|IOException
block|{
name|super
argument_list|(
name|file
argument_list|,
name|colIx
argument_list|,
name|presentStream
argument_list|,
name|codec
argument_list|,
name|bufferSize
argument_list|)
expr_stmt|;
name|Preconditions
operator|.
name|checkNotNull
argument_list|(
name|dataStream
argument_list|,
literal|"DATA stream buffer cannot be null"
argument_list|)
expr_stmt|;
comment|// pass null for codec as stream is already decompressed
name|this
operator|.
name|dataStream
operator|=
name|StreamUtils
operator|.
name|createInStream
argument_list|(
literal|"DATA"
argument_list|,
name|file
argument_list|,
literal|null
argument_list|,
name|bufferSize
argument_list|,
name|dataStream
argument_list|)
expr_stmt|;
name|this
operator|.
name|utils
operator|=
operator|new
name|SerializationUtils
argument_list|()
expr_stmt|;
comment|// position the readers based on the specified row index
name|PositionProvider
name|positionProvider
init|=
operator|new
name|RecordReaderImpl
operator|.
name|PositionProviderImpl
argument_list|(
name|rowIndex
argument_list|)
decl_stmt|;
name|positionReaders
argument_list|(
name|positionProvider
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|positionReaders
parameter_list|(
name|PositionProvider
name|positionProvider
parameter_list|)
throws|throws
name|IOException
block|{
name|super
operator|.
name|positionReaders
argument_list|(
name|positionProvider
argument_list|)
expr_stmt|;
comment|// stream is uncompressed and if file is compressed then skip 1st position in index
if|if
condition|(
name|isFileCompressed
condition|)
block|{
name|positionProvider
operator|.
name|getNext
argument_list|()
expr_stmt|;
block|}
name|inStream
operator|.
name|seek
argument_list|(
name|positionProvider
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|ColumnVector
name|nextVector
parameter_list|(
name|ColumnVector
name|previousVector
parameter_list|,
name|int
name|batchSize
parameter_list|)
throws|throws
name|IOException
block|{
name|DoubleColumnVector
name|result
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|previousVector
operator|==
literal|null
condition|)
block|{
name|result
operator|=
operator|new
name|DoubleColumnVector
argument_list|()
expr_stmt|;
block|}
else|else
block|{
name|result
operator|=
operator|(
name|DoubleColumnVector
operator|)
name|previousVector
expr_stmt|;
block|}
comment|// Read present/isNull stream
name|super
operator|.
name|nextVector
argument_list|(
name|result
argument_list|,
name|batchSize
argument_list|)
expr_stmt|;
comment|// Read value entries based on isNull entries
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|batchSize
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
operator|!
name|result
operator|.
name|isNull
index|[
name|i
index|]
condition|)
block|{
name|result
operator|.
name|vector
index|[
name|i
index|]
operator|=
name|utils
operator|.
name|readFloat
argument_list|(
name|dataStream
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// If the value is not present then set NaN
name|result
operator|.
name|vector
index|[
name|i
index|]
operator|=
name|Double
operator|.
name|NaN
expr_stmt|;
block|}
block|}
comment|// Set isRepeating flag
name|result
operator|.
name|isRepeating
operator|=
literal|true
expr_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
operator|(
name|i
operator|<
name|batchSize
operator|-
literal|1
operator|&&
name|result
operator|.
name|isRepeating
operator|)
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
name|result
operator|.
name|vector
index|[
name|i
index|]
operator|!=
name|result
operator|.
name|vector
index|[
name|i
operator|+
literal|1
index|]
condition|)
block|{
name|result
operator|.
name|isRepeating
operator|=
literal|false
expr_stmt|;
block|}
block|}
return|return
name|result
return|;
block|}
block|}
end_class

end_unit

