begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|plan
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|Serializable
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|metadata
operator|.
name|Partition
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|parse
operator|.
name|BaseSemanticAnalyzer
operator|.
name|TableSpec
import|;
end_import

begin_comment
comment|/**  * Client-side stats aggregator task.  */
end_comment

begin_class
specifier|public
class|class
name|BasicStatsNoJobWork
implements|implements
name|Serializable
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|1L
decl_stmt|;
specifier|private
name|TableSpec
name|tableSpecs
decl_stmt|;
specifier|private
name|boolean
name|statsReliable
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|Partition
argument_list|>
name|pp
decl_stmt|;
specifier|public
name|BasicStatsNoJobWork
parameter_list|(
name|TableSpec
name|tableSpecs
parameter_list|)
block|{
name|this
operator|.
name|tableSpecs
operator|=
name|tableSpecs
expr_stmt|;
block|}
specifier|public
name|TableSpec
name|getTableSpecs
parameter_list|()
block|{
return|return
name|tableSpecs
return|;
block|}
specifier|public
name|void
name|setStatsReliable
parameter_list|(
name|boolean
name|s1
parameter_list|)
block|{
name|statsReliable
operator|=
name|s1
expr_stmt|;
block|}
specifier|public
name|boolean
name|isStatsReliable
parameter_list|()
block|{
return|return
name|statsReliable
return|;
block|}
specifier|public
name|Set
argument_list|<
name|Partition
argument_list|>
name|getPartitions
parameter_list|()
block|{
return|return
name|pp
return|;
block|}
specifier|public
name|void
name|setPartitions
parameter_list|(
name|Set
argument_list|<
name|Partition
argument_list|>
name|partitions
parameter_list|)
block|{
name|pp
operator|=
name|partitions
expr_stmt|;
block|}
block|}
end_class

end_unit

