begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|udf
operator|.
name|generic
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|Description
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|UDFArgumentException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|UDFArgumentTypeException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|metadata
operator|.
name|HiveException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|ObjectInspector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|PrimitiveObjectInspector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|primitive
operator|.
name|PrimitiveObjectInspectorUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|primitive
operator|.
name|PrimitiveObjectInspectorUtils
operator|.
name|PrimitiveGrouping
import|;
end_import

begin_comment
comment|/**  * GenericUDF Class for SQL construct "nullif(a,b)".  */
end_comment

begin_class
annotation|@
name|Description
argument_list|(
name|name
operator|=
literal|"nullif"
argument_list|,
name|value
operator|=
literal|"_FUNC_(a1, a2) - shorthand for: case when a1 = a2 then null else a1"
argument_list|,
name|extended
operator|=
literal|"Example:\n "
operator|+
literal|"SELECT _FUNC_(1,1),_FUNC_(1,2)"
argument_list|)
specifier|public
class|class
name|GenericUDFNullif
extends|extends
name|GenericUDF
block|{
specifier|private
specifier|transient
name|ObjectInspector
index|[]
name|argumentOIs
decl_stmt|;
specifier|private
specifier|transient
name|GenericUDFUtils
operator|.
name|ReturnObjectInspectorResolver
name|returnOIResolver
decl_stmt|;
annotation|@
name|Override
specifier|public
name|ObjectInspector
name|initialize
parameter_list|(
name|ObjectInspector
index|[]
name|arguments
parameter_list|)
throws|throws
name|UDFArgumentException
block|{
name|argumentOIs
operator|=
name|arguments
expr_stmt|;
name|checkArgsSize
argument_list|(
name|arguments
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|returnOIResolver
operator|=
operator|new
name|GenericUDFUtils
operator|.
name|ReturnObjectInspectorResolver
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|returnOIResolver
operator|.
name|update
argument_list|(
name|arguments
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
name|boolean
name|isPrimitive
init|=
operator|(
name|arguments
index|[
literal|0
index|]
operator|instanceof
name|PrimitiveObjectInspector
operator|)
decl_stmt|;
if|if
condition|(
name|isPrimitive
condition|)
block|{
name|PrimitiveObjectInspector
name|primitive0
init|=
operator|(
name|PrimitiveObjectInspector
operator|)
name|arguments
index|[
literal|0
index|]
decl_stmt|;
name|PrimitiveObjectInspector
name|primitive1
init|=
operator|(
name|PrimitiveObjectInspector
operator|)
name|arguments
index|[
literal|1
index|]
decl_stmt|;
name|PrimitiveGrouping
name|pcat0
init|=
name|PrimitiveObjectInspectorUtils
operator|.
name|getPrimitiveGrouping
argument_list|(
name|primitive0
operator|.
name|getPrimitiveCategory
argument_list|()
argument_list|)
decl_stmt|;
name|PrimitiveGrouping
name|pcat1
init|=
name|PrimitiveObjectInspectorUtils
operator|.
name|getPrimitiveGrouping
argument_list|(
name|primitive1
operator|.
name|getPrimitiveCategory
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|pcat0
operator|==
name|PrimitiveGrouping
operator|.
name|VOID_GROUP
condition|)
block|{
throw|throw
operator|new
name|UDFArgumentTypeException
argument_list|(
literal|0
argument_list|,
literal|"NULLIF may not accept types belonging to "
operator|+
name|pcat0
operator|+
literal|" as first argument"
argument_list|)
throw|;
block|}
if|if
condition|(
name|pcat1
operator|!=
name|PrimitiveGrouping
operator|.
name|VOID_GROUP
operator|&&
name|pcat0
operator|!=
name|pcat1
condition|)
block|{
throw|throw
operator|new
name|UDFArgumentTypeException
argument_list|(
literal|1
argument_list|,
literal|"The expressions after NULLIF should belong to the same category: \""
operator|+
name|pcat0
operator|+
literal|"\" is expected but \""
operator|+
name|pcat1
operator|+
literal|"\" is found"
argument_list|)
throw|;
block|}
block|}
else|else
block|{
name|String
name|typeName0
init|=
name|arguments
index|[
literal|0
index|]
operator|.
name|getTypeName
argument_list|()
decl_stmt|;
name|String
name|typeName1
init|=
name|arguments
index|[
literal|1
index|]
operator|.
name|getTypeName
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
name|typeName0
operator|.
name|equals
argument_list|(
name|typeName1
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|UDFArgumentTypeException
argument_list|(
literal|1
argument_list|,
literal|"The expressions after NULLIF should all have the same type: \""
operator|+
name|typeName0
operator|+
literal|"\" is expected but \""
operator|+
name|typeName1
operator|+
literal|"\" is found"
argument_list|)
throw|;
block|}
block|}
return|return
name|returnOIResolver
operator|.
name|get
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|Object
name|evaluate
parameter_list|(
name|DeferredObject
index|[]
name|arguments
parameter_list|)
throws|throws
name|HiveException
block|{
name|Object
name|arg0
init|=
name|arguments
index|[
literal|0
index|]
operator|.
name|get
argument_list|()
decl_stmt|;
name|Object
name|arg1
init|=
name|arguments
index|[
literal|1
index|]
operator|.
name|get
argument_list|()
decl_stmt|;
if|if
condition|(
name|arg0
operator|==
literal|null
operator|||
name|arg1
operator|==
literal|null
condition|)
block|{
return|return
name|arg0
return|;
block|}
name|PrimitiveObjectInspector
name|compareOI
init|=
operator|(
name|PrimitiveObjectInspector
operator|)
name|returnOIResolver
operator|.
name|get
argument_list|()
decl_stmt|;
if|if
condition|(
name|PrimitiveObjectInspectorUtils
operator|.
name|comparePrimitiveObjects
argument_list|(
name|arg0
argument_list|,
name|compareOI
argument_list|,
name|returnOIResolver
operator|.
name|convertIfNecessary
argument_list|(
name|arg1
argument_list|,
name|argumentOIs
index|[
literal|1
index|]
argument_list|,
literal|false
argument_list|)
argument_list|,
name|compareOI
argument_list|)
condition|)
block|{
return|return
literal|null
return|;
block|}
return|return
name|arg0
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getDisplayString
parameter_list|(
name|String
index|[]
name|children
parameter_list|)
block|{
return|return
name|getStandardDisplayString
argument_list|(
literal|"NULLIF"
argument_list|,
name|children
argument_list|,
literal|","
argument_list|)
return|;
block|}
block|}
end_class

end_unit

