begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hive
operator|.
name|service
operator|.
name|auth
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|sasl
operator|.
name|AuthenticationException
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jpam
operator|.
name|Pam
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|conf
operator|.
name|HiveConf
import|;
end_import

begin_class
specifier|public
class|class
name|PamAuthenticationProviderImpl
implements|implements
name|PasswdAuthenticationProvider
block|{
specifier|private
specifier|final
name|String
name|pamServiceNames
decl_stmt|;
name|PamAuthenticationProviderImpl
parameter_list|()
block|{
name|HiveConf
name|conf
init|=
operator|new
name|HiveConf
argument_list|()
decl_stmt|;
name|pamServiceNames
operator|=
name|conf
operator|.
name|getVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PAM_SERVICES
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|Authenticate
parameter_list|(
name|String
name|user
parameter_list|,
name|String
name|password
parameter_list|)
throws|throws
name|AuthenticationException
block|{
if|if
condition|(
name|pamServiceNames
operator|==
literal|null
operator|||
name|pamServiceNames
operator|.
name|trim
argument_list|()
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|AuthenticationException
argument_list|(
literal|"No PAM services are set."
argument_list|)
throw|;
block|}
name|String
index|[]
name|pamServices
init|=
name|pamServiceNames
operator|.
name|split
argument_list|(
literal|","
argument_list|)
decl_stmt|;
for|for
control|(
name|String
name|pamService
range|:
name|pamServices
control|)
block|{
name|Pam
name|pam
init|=
operator|new
name|Pam
argument_list|(
name|pamService
argument_list|)
decl_stmt|;
name|boolean
name|isAuthenticated
init|=
name|pam
operator|.
name|authenticateSuccessful
argument_list|(
name|user
argument_list|,
name|password
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|isAuthenticated
condition|)
block|{
throw|throw
operator|new
name|AuthenticationException
argument_list|(
literal|"Error authenticating with the PAM service: "
operator|+
name|pamService
argument_list|)
throw|;
block|}
block|}
block|}
block|}
end_class

end_unit

