begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|metastore
operator|.
name|model
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_class
specifier|public
class|class
name|MWMTrigger
block|{
specifier|private
name|MWMResourcePlan
name|resourcePlan
decl_stmt|;
specifier|private
name|String
name|name
decl_stmt|;
specifier|private
name|String
name|triggerExpression
decl_stmt|;
specifier|private
name|String
name|actionExpression
decl_stmt|;
comment|// This is integer because in Derby DN converts boolean to char, breaking sysdb.
specifier|private
name|int
name|isInUnmanaged
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|MWMPool
argument_list|>
name|pools
decl_stmt|;
specifier|public
name|MWMTrigger
parameter_list|(
name|MWMResourcePlan
name|resourcePlan
parameter_list|,
name|String
name|name
parameter_list|,
name|String
name|triggerExpression
parameter_list|,
name|String
name|actionExpression
parameter_list|,
name|Set
argument_list|<
name|MWMPool
argument_list|>
name|pools
parameter_list|,
name|boolean
name|isInUnmanaged
parameter_list|)
block|{
name|this
operator|.
name|resourcePlan
operator|=
name|resourcePlan
expr_stmt|;
name|this
operator|.
name|name
operator|=
name|name
expr_stmt|;
name|this
operator|.
name|triggerExpression
operator|=
name|triggerExpression
expr_stmt|;
name|this
operator|.
name|actionExpression
operator|=
name|actionExpression
expr_stmt|;
name|this
operator|.
name|pools
operator|=
name|pools
expr_stmt|;
name|this
operator|.
name|isInUnmanaged
operator|=
name|isInUnmanaged
condition|?
literal|1
else|:
literal|0
expr_stmt|;
block|}
specifier|public
name|MWMResourcePlan
name|getResourcePlan
parameter_list|()
block|{
return|return
name|resourcePlan
return|;
block|}
specifier|public
name|void
name|setResourcePlan
parameter_list|(
name|MWMResourcePlan
name|resourcePlan
parameter_list|)
block|{
name|this
operator|.
name|resourcePlan
operator|=
name|resourcePlan
expr_stmt|;
block|}
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|name
return|;
block|}
specifier|public
name|void
name|setName
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|this
operator|.
name|name
operator|=
name|name
expr_stmt|;
block|}
specifier|public
name|String
name|getTriggerExpression
parameter_list|()
block|{
return|return
name|triggerExpression
return|;
block|}
specifier|public
name|void
name|setTriggerExpression
parameter_list|(
name|String
name|triggerExpression
parameter_list|)
block|{
name|this
operator|.
name|triggerExpression
operator|=
name|triggerExpression
expr_stmt|;
block|}
specifier|public
name|String
name|getActionExpression
parameter_list|()
block|{
return|return
name|actionExpression
return|;
block|}
specifier|public
name|void
name|setActionExpression
parameter_list|(
name|String
name|actionExpression
parameter_list|)
block|{
name|this
operator|.
name|actionExpression
operator|=
name|actionExpression
expr_stmt|;
block|}
specifier|public
name|Set
argument_list|<
name|MWMPool
argument_list|>
name|getPools
parameter_list|()
block|{
return|return
name|pools
return|;
block|}
specifier|public
name|void
name|setPools
parameter_list|(
name|Set
argument_list|<
name|MWMPool
argument_list|>
name|pools
parameter_list|)
block|{
name|this
operator|.
name|pools
operator|=
name|pools
expr_stmt|;
block|}
specifier|public
name|boolean
name|getIsInUnmanaged
parameter_list|()
block|{
return|return
name|isInUnmanaged
operator|==
literal|1
return|;
block|}
specifier|public
name|void
name|setIsInUnmanaged
parameter_list|(
name|boolean
name|isInUnmanaged
parameter_list|)
block|{
name|this
operator|.
name|isInUnmanaged
operator|=
name|isInUnmanaged
condition|?
literal|1
else|:
literal|0
expr_stmt|;
block|}
block|}
end_class

end_unit

