begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|optimizer
operator|.
name|index
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|Serializable
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedHashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedHashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|Log
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|LogFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|conf
operator|.
name|HiveConf
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|metastore
operator|.
name|api
operator|.
name|FieldSchema
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|metastore
operator|.
name|api
operator|.
name|Index
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|metastore
operator|.
name|api
operator|.
name|StorageDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|Operator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|TableScanOperator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|index
operator|.
name|AggregateIndexHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|metadata
operator|.
name|Hive
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|metadata
operator|.
name|HiveException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|metadata
operator|.
name|Partition
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|metadata
operator|.
name|Table
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|optimizer
operator|.
name|IndexUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|optimizer
operator|.
name|Transform
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|parse
operator|.
name|OpParseContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|parse
operator|.
name|ParseContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|parse
operator|.
name|SemanticException
import|;
end_import

begin_comment
comment|/**  * RewriteGBUsingIndex is implemented as one of the Rule-based Optimizations.  * Implements optimizations for GroupBy clause rewrite using aggregate index.  * This optimization rewrites GroupBy query over base table to the query over simple table-scan  * over index table, if there is index on the group by key(s) or the distinct column(s).  * E.g.  *<code>  *   select count(key)  *   from table  *   group by key;  *</code>  *  to  *<code>  *   select sum(_count_Of_key)  *   from idx_table  *   group by key;  *</code>  *  *  The rewrite supports following queries:  *<ul>  *<li> Queries having only those col refs that are in the index key.  *<li> Queries that have index key col refs  *<ul>  *<li> in SELECT  *<li> in WHERE  *<li> in GROUP BY  *</ul>  *<li> Queries with agg func COUNT(index key col ref) in SELECT  *<li> Queries with SELECT DISTINCT index_key_col_refs  *<li> Queries having a subquery satisfying above condition (only the subquery is rewritten)  *</ul>  *  *  @see AggregateIndexHandler  *  @see IndexUtils  *  @see RewriteCanApplyCtx  *  @see RewriteCanApplyProcFactory  *  @see RewriteParseContextGenerator  *  @see RewriteQueryUsingAggregateIndexCtx  *  @see RewriteQueryUsingAggregateIndex  *  For test cases, @see ql_rewrite_gbtoidx.q  */
end_comment

begin_class
specifier|public
class|class
name|RewriteGBUsingIndex
implements|implements
name|Transform
block|{
specifier|private
name|ParseContext
name|parseContext
decl_stmt|;
specifier|private
name|Hive
name|hiveDb
decl_stmt|;
specifier|private
name|HiveConf
name|hiveConf
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|Log
name|LOG
init|=
name|LogFactory
operator|.
name|getLog
argument_list|(
name|RewriteGBUsingIndex
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|)
decl_stmt|;
comment|/*    * Stores the list of top TableScanOperator names for which the rewrite    * can be applied and the action that needs to be performed for operator tree    * starting from this TableScanOperator    */
specifier|private
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|RewriteCanApplyCtx
argument_list|>
name|tsOpToProcess
init|=
operator|new
name|LinkedHashMap
argument_list|<
name|String
argument_list|,
name|RewriteCanApplyCtx
argument_list|>
argument_list|()
decl_stmt|;
comment|//Name of the current table on which rewrite is being performed
specifier|private
name|String
name|baseTableName
init|=
literal|null
decl_stmt|;
comment|//Name of the current index which is used for rewrite
specifier|private
name|String
name|indexTableName
init|=
literal|null
decl_stmt|;
comment|//Index Validation Variables
specifier|private
specifier|static
specifier|final
name|String
name|IDX_BUCKET_COL
init|=
literal|"_bucketname"
decl_stmt|;
specifier|private
specifier|static
specifier|final
name|String
name|IDX_OFFSETS_ARRAY_COL
init|=
literal|"_offsets"
decl_stmt|;
annotation|@
name|Override
specifier|public
name|ParseContext
name|transform
parameter_list|(
name|ParseContext
name|pctx
parameter_list|)
throws|throws
name|SemanticException
block|{
name|parseContext
operator|=
name|pctx
expr_stmt|;
name|hiveConf
operator|=
name|parseContext
operator|.
name|getConf
argument_list|()
expr_stmt|;
try|try
block|{
name|hiveDb
operator|=
name|Hive
operator|.
name|get
argument_list|(
name|hiveConf
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|HiveException
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|util
operator|.
name|StringUtils
operator|.
name|stringifyException
argument_list|(
name|e
argument_list|)
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|SemanticException
argument_list|(
name|e
operator|.
name|getMessage
argument_list|()
argument_list|,
name|e
argument_list|)
throw|;
block|}
comment|// Don't try to index optimize the query to build the index
name|HiveConf
operator|.
name|setBoolVar
argument_list|(
name|hiveConf
argument_list|,
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVEOPTINDEXFILTER
argument_list|,
literal|false
argument_list|)
expr_stmt|;
comment|/* Check if the input query passes all the tests to be eligible for a rewrite      * If yes, rewrite original query; else, return the current parseContext      */
if|if
condition|(
name|shouldApplyOptimization
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"Rewriting Original Query using "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
name|rewriteOriginalQuery
argument_list|()
expr_stmt|;
block|}
return|return
name|parseContext
return|;
block|}
specifier|private
name|String
name|getName
parameter_list|()
block|{
return|return
literal|"RewriteGBUsingIndex"
return|;
block|}
comment|/**    * We traverse the current operator tree to check for conditions in which the    * optimization cannot be applied.    *    * At the end, we check if all conditions have passed for rewrite. If yes, we    * determine if the the index is usable for rewrite. Else, we log the condition which    * did not meet the rewrite criterion.    *    * @return    * @throws SemanticException    */
name|boolean
name|shouldApplyOptimization
parameter_list|()
throws|throws
name|SemanticException
block|{
name|boolean
name|canApply
init|=
literal|false
decl_stmt|;
if|if
condition|(
name|ifQueryHasMultipleTables
argument_list|()
condition|)
block|{
comment|//We do not apply this optimization for this case as of now.
return|return
literal|false
return|;
block|}
else|else
block|{
comment|/*      * This code iterates over each TableScanOperator from the topOps map from ParseContext.      * For each operator tree originating from this top TableScanOperator, we determine      * if the optimization can be applied. If yes, we add the name of the top table to      * the tsOpToProcess to apply rewrite later on.      * */
name|Map
argument_list|<
name|TableScanOperator
argument_list|,
name|Table
argument_list|>
name|topToTable
init|=
name|parseContext
operator|.
name|getTopToTable
argument_list|()
decl_stmt|;
name|Iterator
argument_list|<
name|TableScanOperator
argument_list|>
name|topOpItr
init|=
name|topToTable
operator|.
name|keySet
argument_list|()
operator|.
name|iterator
argument_list|()
decl_stmt|;
while|while
condition|(
name|topOpItr
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|TableScanOperator
name|topOp
init|=
name|topOpItr
operator|.
name|next
argument_list|()
decl_stmt|;
name|Table
name|table
init|=
name|topToTable
operator|.
name|get
argument_list|(
name|topOp
argument_list|)
decl_stmt|;
name|baseTableName
operator|=
name|table
operator|.
name|getTableName
argument_list|()
expr_stmt|;
name|Map
argument_list|<
name|Table
argument_list|,
name|List
argument_list|<
name|Index
argument_list|>
argument_list|>
name|indexes
init|=
name|getIndexesForRewrite
argument_list|()
decl_stmt|;
if|if
condition|(
name|indexes
operator|==
literal|null
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Error getting valid indexes for rewrite, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization"
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|indexes
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"No Valid Index Found to apply Rewrite, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization"
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
else|else
block|{
comment|//we need to check if the base table has confirmed or unknown partitions
if|if
condition|(
name|parseContext
operator|.
name|getOpToPartList
argument_list|()
operator|!=
literal|null
operator|&&
name|parseContext
operator|.
name|getOpToPartList
argument_list|()
operator|.
name|size
argument_list|()
operator|>
literal|0
condition|)
block|{
comment|//if base table has partitions, we need to check if index is built for
comment|//all partitions. If not, then we do not apply the optimization
if|if
condition|(
name|checkIfIndexBuiltOnAllTablePartitions
argument_list|(
name|topOp
argument_list|,
name|indexes
argument_list|)
condition|)
block|{
comment|//check if rewrite can be applied for operator tree
comment|//if partitions condition returns true
name|canApply
operator|=
name|checkIfRewriteCanBeApplied
argument_list|(
name|topOp
argument_list|,
name|table
argument_list|,
name|indexes
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Index is not built for all table partitions, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization"
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
block|}
else|else
block|{
comment|//check if rewrite can be applied for operator tree
comment|//if there are no partitions on base table
name|canApply
operator|=
name|checkIfRewriteCanBeApplied
argument_list|(
name|topOp
argument_list|,
name|table
argument_list|,
name|indexes
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
return|return
name|canApply
return|;
block|}
comment|/**    * This methods checks if rewrite can be applied using the index and also    * verifies all conditions of the operator tree.    *    * @param topOp - TableScanOperator for a single the operator tree branch    * @param indexes - Map of a table and list of indexes on it    * @return - true if rewrite can be applied on the current branch; false otherwise    * @throws SemanticException    */
specifier|private
name|boolean
name|checkIfRewriteCanBeApplied
parameter_list|(
name|TableScanOperator
name|topOp
parameter_list|,
name|Table
name|baseTable
parameter_list|,
name|Map
argument_list|<
name|Table
argument_list|,
name|List
argument_list|<
name|Index
argument_list|>
argument_list|>
name|indexes
parameter_list|)
throws|throws
name|SemanticException
block|{
name|boolean
name|canApply
init|=
literal|false
decl_stmt|;
comment|//Context for checking if this optimization can be applied to the input query
name|RewriteCanApplyCtx
name|canApplyCtx
init|=
name|RewriteCanApplyCtx
operator|.
name|getInstance
argument_list|(
name|parseContext
argument_list|)
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Operator
argument_list|<
name|?
extends|extends
name|Serializable
argument_list|>
argument_list|>
name|topOps
init|=
name|parseContext
operator|.
name|getTopOps
argument_list|()
decl_stmt|;
name|canApplyCtx
operator|.
name|setBaseTableName
argument_list|(
name|baseTableName
argument_list|)
expr_stmt|;
name|canApplyCtx
operator|.
name|populateRewriteVars
argument_list|(
name|topOp
argument_list|)
expr_stmt|;
name|Map
argument_list|<
name|Index
argument_list|,
name|Set
argument_list|<
name|String
argument_list|>
argument_list|>
name|indexTableMap
init|=
name|getIndexToKeysMap
argument_list|(
name|indexes
operator|.
name|get
argument_list|(
name|baseTable
argument_list|)
argument_list|)
decl_stmt|;
name|Iterator
argument_list|<
name|Index
argument_list|>
name|indexMapItr
init|=
name|indexTableMap
operator|.
name|keySet
argument_list|()
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|Index
name|index
init|=
literal|null
decl_stmt|;
while|while
condition|(
name|indexMapItr
operator|.
name|hasNext
argument_list|()
condition|)
block|{
comment|//we rewrite the original query using the first valid index encountered
comment|//this can be changed if we have a better mechanism to
comment|//decide which index will produce a better rewrite
name|index
operator|=
name|indexMapItr
operator|.
name|next
argument_list|()
expr_stmt|;
name|canApply
operator|=
name|canApplyCtx
operator|.
name|isIndexUsableForQueryBranchRewrite
argument_list|(
name|index
argument_list|,
name|indexTableMap
operator|.
name|get
argument_list|(
name|index
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|canApply
condition|)
block|{
name|canApply
operator|=
name|checkIfAllRewriteCriteriaIsMet
argument_list|(
name|canApplyCtx
argument_list|)
expr_stmt|;
comment|//break here if any valid index is found to apply rewrite
if|if
condition|(
name|canApply
condition|)
block|{
comment|//check if aggregation function is set.
comment|//If not, set it using the only indexed column
if|if
condition|(
name|canApplyCtx
operator|.
name|getAggFunction
argument_list|()
operator|==
literal|null
condition|)
block|{
comment|//strip of the start and end braces [...]
name|String
name|aggregationFunction
init|=
name|indexTableMap
operator|.
name|get
argument_list|(
name|index
argument_list|)
operator|.
name|toString
argument_list|()
decl_stmt|;
name|aggregationFunction
operator|=
name|aggregationFunction
operator|.
name|substring
argument_list|(
literal|1
argument_list|,
name|aggregationFunction
operator|.
name|length
argument_list|()
operator|-
literal|1
argument_list|)
expr_stmt|;
name|canApplyCtx
operator|.
name|setAggFunction
argument_list|(
literal|"_count_Of_"
operator|+
name|aggregationFunction
operator|+
literal|""
argument_list|)
expr_stmt|;
block|}
block|}
break|break;
block|}
block|}
name|indexTableName
operator|=
name|index
operator|.
name|getIndexTableName
argument_list|()
expr_stmt|;
if|if
condition|(
name|canApply
operator|&&
name|topOps
operator|.
name|containsValue
argument_list|(
name|topOp
argument_list|)
condition|)
block|{
name|Iterator
argument_list|<
name|String
argument_list|>
name|topOpNamesItr
init|=
name|topOps
operator|.
name|keySet
argument_list|()
operator|.
name|iterator
argument_list|()
decl_stmt|;
while|while
condition|(
name|topOpNamesItr
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|String
name|topOpName
init|=
name|topOpNamesItr
operator|.
name|next
argument_list|()
decl_stmt|;
if|if
condition|(
name|topOps
operator|.
name|get
argument_list|(
name|topOpName
argument_list|)
operator|.
name|equals
argument_list|(
name|topOp
argument_list|)
condition|)
block|{
name|tsOpToProcess
operator|.
name|put
argument_list|(
name|topOpName
argument_list|,
name|canApplyCtx
argument_list|)
expr_stmt|;
block|}
block|}
block|}
if|if
condition|(
name|tsOpToProcess
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
name|canApply
operator|=
literal|false
expr_stmt|;
block|}
else|else
block|{
name|canApply
operator|=
literal|true
expr_stmt|;
block|}
return|return
name|canApply
return|;
block|}
comment|/**    * This block of code iterates over the topToTable map from ParseContext    * to determine if the query has a scan over multiple tables.    * @return    */
name|boolean
name|ifQueryHasMultipleTables
parameter_list|()
block|{
name|Map
argument_list|<
name|TableScanOperator
argument_list|,
name|Table
argument_list|>
name|topToTable
init|=
name|parseContext
operator|.
name|getTopToTable
argument_list|()
decl_stmt|;
name|Iterator
argument_list|<
name|Table
argument_list|>
name|valuesItr
init|=
name|topToTable
operator|.
name|values
argument_list|()
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|Set
argument_list|<
name|String
argument_list|>
name|tableNameSet
init|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
while|while
condition|(
name|valuesItr
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|Table
name|table
init|=
name|valuesItr
operator|.
name|next
argument_list|()
decl_stmt|;
name|tableNameSet
operator|.
name|add
argument_list|(
name|table
operator|.
name|getTableName
argument_list|()
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|tableNameSet
operator|.
name|size
argument_list|()
operator|>
literal|1
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Query has more than one table "
operator|+
literal|"that is not supported with "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|true
return|;
block|}
return|return
literal|false
return|;
block|}
comment|/**    * Get a list of indexes which can be used for rewrite.    * @return    * @throws SemanticException    */
specifier|private
name|Map
argument_list|<
name|Table
argument_list|,
name|List
argument_list|<
name|Index
argument_list|>
argument_list|>
name|getIndexesForRewrite
parameter_list|()
throws|throws
name|SemanticException
block|{
name|List
argument_list|<
name|String
argument_list|>
name|supportedIndexes
init|=
operator|new
name|ArrayList
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
name|supportedIndexes
operator|.
name|add
argument_list|(
name|AggregateIndexHandler
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
comment|// query the metastore to know what columns we have indexed
name|Collection
argument_list|<
name|Table
argument_list|>
name|topTables
init|=
name|parseContext
operator|.
name|getTopToTable
argument_list|()
operator|.
name|values
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|Table
argument_list|,
name|List
argument_list|<
name|Index
argument_list|>
argument_list|>
name|indexes
init|=
operator|new
name|HashMap
argument_list|<
name|Table
argument_list|,
name|List
argument_list|<
name|Index
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|Table
name|tbl
range|:
name|topTables
control|)
block|{
name|List
argument_list|<
name|Index
argument_list|>
name|tblIndexes
init|=
name|IndexUtils
operator|.
name|getIndexes
argument_list|(
name|tbl
argument_list|,
name|supportedIndexes
argument_list|)
decl_stmt|;
if|if
condition|(
name|tblIndexes
operator|.
name|size
argument_list|()
operator|>
literal|0
condition|)
block|{
name|indexes
operator|.
name|put
argument_list|(
name|tbl
argument_list|,
name|tblIndexes
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|indexes
return|;
block|}
comment|/**    * This method checks if the index is built on all partitions of the base    * table. If not, then the method returns false as we do not apply optimization    * for this case.    * @param tableScan    * @param indexes    * @return    * @throws SemanticException    */
specifier|private
name|boolean
name|checkIfIndexBuiltOnAllTablePartitions
parameter_list|(
name|TableScanOperator
name|tableScan
parameter_list|,
name|Map
argument_list|<
name|Table
argument_list|,
name|List
argument_list|<
name|Index
argument_list|>
argument_list|>
name|indexes
parameter_list|)
throws|throws
name|SemanticException
block|{
comment|// check if we have indexes on all partitions in this table scan
name|Set
argument_list|<
name|Partition
argument_list|>
name|queryPartitions
decl_stmt|;
try|try
block|{
name|queryPartitions
operator|=
name|IndexUtils
operator|.
name|checkPartitionsCoveredByIndex
argument_list|(
name|tableScan
argument_list|,
name|parseContext
argument_list|,
name|indexes
argument_list|)
expr_stmt|;
if|if
condition|(
name|queryPartitions
operator|==
literal|null
condition|)
block|{
comment|// partitions not covered
return|return
literal|false
return|;
block|}
block|}
catch|catch
parameter_list|(
name|HiveException
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"Fatal Error: problem accessing metastore"
argument_list|,
name|e
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|SemanticException
argument_list|(
name|e
argument_list|)
throw|;
block|}
if|if
condition|(
name|queryPartitions
operator|.
name|size
argument_list|()
operator|!=
literal|0
condition|)
block|{
return|return
literal|true
return|;
block|}
return|return
literal|false
return|;
block|}
comment|/**    * This code block iterates over indexes on the table and populates the indexToKeys map    * for all the indexes that satisfy the rewrite criteria.    * @param indexTables    * @return    * @throws SemanticException    */
name|Map
argument_list|<
name|Index
argument_list|,
name|Set
argument_list|<
name|String
argument_list|>
argument_list|>
name|getIndexToKeysMap
parameter_list|(
name|List
argument_list|<
name|Index
argument_list|>
name|indexTables
parameter_list|)
throws|throws
name|SemanticException
block|{
name|Index
name|index
init|=
literal|null
decl_stmt|;
name|Hive
name|hiveInstance
init|=
name|hiveDb
decl_stmt|;
name|Map
argument_list|<
name|Index
argument_list|,
name|Set
argument_list|<
name|String
argument_list|>
argument_list|>
name|indexToKeysMap
init|=
operator|new
name|LinkedHashMap
argument_list|<
name|Index
argument_list|,
name|Set
argument_list|<
name|String
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|idxCtr
init|=
literal|0
init|;
name|idxCtr
operator|<
name|indexTables
operator|.
name|size
argument_list|()
condition|;
name|idxCtr
operator|++
control|)
block|{
specifier|final
name|Set
argument_list|<
name|String
argument_list|>
name|indexKeyNames
init|=
operator|new
name|LinkedHashSet
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
name|index
operator|=
name|indexTables
operator|.
name|get
argument_list|(
name|idxCtr
argument_list|)
expr_stmt|;
comment|//Getting index key columns
name|StorageDescriptor
name|sd
init|=
name|index
operator|.
name|getSd
argument_list|()
decl_stmt|;
name|List
argument_list|<
name|FieldSchema
argument_list|>
name|idxColList
init|=
name|sd
operator|.
name|getCols
argument_list|()
decl_stmt|;
for|for
control|(
name|FieldSchema
name|fieldSchema
range|:
name|idxColList
control|)
block|{
name|indexKeyNames
operator|.
name|add
argument_list|(
name|fieldSchema
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
assert|assert
name|indexKeyNames
operator|.
name|size
argument_list|()
operator|==
literal|1
assert|;
comment|// Check that the index schema is as expected. This code block should
comment|// catch problems of this rewrite breaking when the AggregateIndexHandler
comment|// index is changed.
name|List
argument_list|<
name|String
argument_list|>
name|idxTblColNames
init|=
operator|new
name|ArrayList
argument_list|<
name|String
argument_list|>
argument_list|()
decl_stmt|;
try|try
block|{
name|Table
name|idxTbl
init|=
name|hiveInstance
operator|.
name|getTable
argument_list|(
name|index
operator|.
name|getDbName
argument_list|()
argument_list|,
name|index
operator|.
name|getIndexTableName
argument_list|()
argument_list|)
decl_stmt|;
for|for
control|(
name|FieldSchema
name|idxTblCol
range|:
name|idxTbl
operator|.
name|getCols
argument_list|()
control|)
block|{
name|idxTblColNames
operator|.
name|add
argument_list|(
name|idxTblCol
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|HiveException
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"Got exception while locating index table, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization"
argument_list|)
expr_stmt|;
name|LOG
operator|.
name|error
argument_list|(
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|util
operator|.
name|StringUtils
operator|.
name|stringifyException
argument_list|(
name|e
argument_list|)
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|SemanticException
argument_list|(
name|e
operator|.
name|getMessage
argument_list|()
argument_list|,
name|e
argument_list|)
throw|;
block|}
assert|assert
operator|(
name|idxTblColNames
operator|.
name|contains
argument_list|(
name|IDX_BUCKET_COL
argument_list|)
operator|)
assert|;
assert|assert
operator|(
name|idxTblColNames
operator|.
name|contains
argument_list|(
name|IDX_OFFSETS_ARRAY_COL
argument_list|)
operator|)
assert|;
comment|// we add all index tables which can be used for rewrite
comment|// and defer the decision of using a particular index for later
comment|// this is to allow choosing a index if a better mechanism is
comment|// designed later to chose a better rewrite
name|indexToKeysMap
operator|.
name|put
argument_list|(
name|index
argument_list|,
name|indexKeyNames
argument_list|)
expr_stmt|;
block|}
return|return
name|indexToKeysMap
return|;
block|}
comment|/**    * Method to rewrite the input query if all optimization criteria is passed.    * The method iterates over the tsOpToProcess {@link ArrayList} to apply the rewrites    * @throws SemanticException    *    */
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unchecked"
argument_list|)
specifier|private
name|void
name|rewriteOriginalQuery
parameter_list|()
throws|throws
name|SemanticException
block|{
name|Map
argument_list|<
name|String
argument_list|,
name|Operator
argument_list|<
name|?
extends|extends
name|Serializable
argument_list|>
argument_list|>
name|topOpMap
init|=
operator|(
name|HashMap
argument_list|<
name|String
argument_list|,
name|Operator
argument_list|<
name|?
extends|extends
name|Serializable
argument_list|>
argument_list|>
operator|)
name|parseContext
operator|.
name|getTopOps
argument_list|()
operator|.
name|clone
argument_list|()
decl_stmt|;
name|Iterator
argument_list|<
name|String
argument_list|>
name|tsOpItr
init|=
name|tsOpToProcess
operator|.
name|keySet
argument_list|()
operator|.
name|iterator
argument_list|()
decl_stmt|;
while|while
condition|(
name|tsOpItr
operator|.
name|hasNext
argument_list|()
condition|)
block|{
name|baseTableName
operator|=
name|tsOpItr
operator|.
name|next
argument_list|()
expr_stmt|;
name|RewriteCanApplyCtx
name|canApplyCtx
init|=
name|tsOpToProcess
operator|.
name|get
argument_list|(
name|baseTableName
argument_list|)
decl_stmt|;
name|TableScanOperator
name|topOp
init|=
operator|(
name|TableScanOperator
operator|)
name|topOpMap
operator|.
name|get
argument_list|(
name|baseTableName
argument_list|)
decl_stmt|;
name|RewriteQueryUsingAggregateIndexCtx
name|rewriteQueryCtx
init|=
name|RewriteQueryUsingAggregateIndexCtx
operator|.
name|getInstance
argument_list|(
name|parseContext
argument_list|,
name|hiveDb
argument_list|,
name|indexTableName
argument_list|,
name|baseTableName
argument_list|,
name|canApplyCtx
operator|.
name|getAggFunction
argument_list|()
argument_list|)
decl_stmt|;
name|rewriteQueryCtx
operator|.
name|invokeRewriteQueryProc
argument_list|(
name|topOp
argument_list|)
expr_stmt|;
name|parseContext
operator|=
name|rewriteQueryCtx
operator|.
name|getParseContext
argument_list|()
expr_stmt|;
name|parseContext
operator|.
name|setOpParseCtx
argument_list|(
operator|(
name|LinkedHashMap
argument_list|<
name|Operator
argument_list|<
name|?
extends|extends
name|Serializable
argument_list|>
argument_list|,
name|OpParseContext
argument_list|>
operator|)
name|rewriteQueryCtx
operator|.
name|getOpc
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|LOG
operator|.
name|info
argument_list|(
literal|"Finished Rewriting query"
argument_list|)
expr_stmt|;
block|}
comment|/**    * This method logs the reason for which we cannot apply the rewrite optimization.    * @return    */
name|boolean
name|checkIfAllRewriteCriteriaIsMet
parameter_list|(
name|RewriteCanApplyCtx
name|canApplyCtx
parameter_list|)
block|{
if|if
condition|(
name|canApplyCtx
operator|.
name|getAggFuncCnt
argument_list|()
operator|>
literal|1
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"More than 1 agg funcs: "
operator|+
literal|"Not supported by "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isAggFuncIsNotCount
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Agg func other than count is "
operator|+
literal|"not supported by "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isCountOnAllCols
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Currently count function needs group by on key columns. This is a count(*) case.,"
operator|+
literal|"Cannot apply this "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isCountOfOne
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Currently count function needs group by on key columns. This is a count(1) case.,"
operator|+
literal|"Cannot apply this "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isAggFuncColsFetchException
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Got exception while locating child col refs "
operator|+
literal|"of agg func, skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isWhrClauseColsFetchException
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Got exception while locating child col refs for where clause, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isSelClauseColsFetchException
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Got exception while locating child col refs for select list, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
name|canApplyCtx
operator|.
name|isGbyKeysFetchException
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Got exception while locating child col refs for GroupBy key, "
operator|+
literal|"skipping "
operator|+
name|getName
argument_list|()
operator|+
literal|" optimization."
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
return|return
literal|true
return|;
block|}
block|}
end_class

end_unit

