begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|accumulo
operator|.
name|predicate
operator|.
name|compare
package|;
end_package

begin_comment
comment|/**  * Wraps call to lessThanOrEqual over {@link PrimitiveComparison} instance.  *  * Used by {@link org.apache.hadoop.hive.accumulo.predicate.PrimitiveComparisonFilter}  */
end_comment

begin_class
specifier|public
class|class
name|LessThanOrEqual
implements|implements
name|CompareOp
block|{
specifier|private
name|PrimitiveComparison
name|comp
decl_stmt|;
specifier|public
name|LessThanOrEqual
parameter_list|()
block|{}
specifier|public
name|LessThanOrEqual
parameter_list|(
name|PrimitiveComparison
name|comp
parameter_list|)
block|{
name|this
operator|.
name|comp
operator|=
name|comp
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|setPrimitiveCompare
parameter_list|(
name|PrimitiveComparison
name|comp
parameter_list|)
block|{
name|this
operator|.
name|comp
operator|=
name|comp
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|PrimitiveComparison
name|getPrimitiveCompare
parameter_list|()
block|{
return|return
name|comp
return|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|accept
parameter_list|(
name|byte
index|[]
name|val
parameter_list|)
block|{
return|return
name|comp
operator|.
name|lessThanOrEqual
argument_list|(
name|val
argument_list|)
return|;
block|}
block|}
end_class

end_unit

