begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|expressions
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|BytesColumnVector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|DoubleColumnVector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|LongColumnVector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|exec
operator|.
name|vector
operator|.
name|VectorizedRowBatch
import|;
end_import

begin_comment
comment|/**  * Constant is represented as a vector with repeating values.  */
end_comment

begin_class
specifier|public
class|class
name|ConstantVectorExpression
extends|extends
name|VectorExpression
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|1L
decl_stmt|;
specifier|private
specifier|static
enum|enum
name|Type
block|{
name|LONG
block|,
name|DOUBLE
block|,
name|BYTES
block|}
specifier|private
name|int
name|outputColumn
decl_stmt|;
specifier|protected
name|long
name|longValue
init|=
literal|0
decl_stmt|;
specifier|private
name|double
name|doubleValue
init|=
literal|0
decl_stmt|;
specifier|private
name|byte
index|[]
name|bytesValue
init|=
literal|null
decl_stmt|;
specifier|private
name|String
name|typeString
decl_stmt|;
specifier|private
specifier|transient
name|Type
name|type
decl_stmt|;
specifier|private
specifier|transient
name|int
name|bytesValueLength
init|=
literal|0
decl_stmt|;
specifier|public
name|ConstantVectorExpression
parameter_list|()
block|{
name|super
argument_list|()
expr_stmt|;
block|}
name|ConstantVectorExpression
parameter_list|(
name|int
name|outputColumn
parameter_list|,
name|String
name|typeString
parameter_list|)
block|{
name|this
argument_list|()
expr_stmt|;
name|this
operator|.
name|outputColumn
operator|=
name|outputColumn
expr_stmt|;
name|setTypeString
argument_list|(
name|typeString
argument_list|)
expr_stmt|;
block|}
specifier|public
name|ConstantVectorExpression
parameter_list|(
name|int
name|outputColumn
parameter_list|,
name|long
name|value
parameter_list|)
block|{
name|this
argument_list|(
name|outputColumn
argument_list|,
literal|"long"
argument_list|)
expr_stmt|;
name|this
operator|.
name|longValue
operator|=
name|value
expr_stmt|;
block|}
specifier|public
name|ConstantVectorExpression
parameter_list|(
name|int
name|outputColumn
parameter_list|,
name|double
name|value
parameter_list|)
block|{
name|this
argument_list|(
name|outputColumn
argument_list|,
literal|"double"
argument_list|)
expr_stmt|;
name|this
operator|.
name|doubleValue
operator|=
name|value
expr_stmt|;
block|}
specifier|public
name|ConstantVectorExpression
parameter_list|(
name|int
name|outputColumn
parameter_list|,
name|byte
index|[]
name|value
parameter_list|)
block|{
name|this
argument_list|(
name|outputColumn
argument_list|,
literal|"string"
argument_list|)
expr_stmt|;
name|setBytesValue
argument_list|(
name|value
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|evaluateLong
parameter_list|(
name|VectorizedRowBatch
name|vrg
parameter_list|)
block|{
name|LongColumnVector
name|cv
init|=
operator|(
name|LongColumnVector
operator|)
name|vrg
operator|.
name|cols
index|[
name|outputColumn
index|]
decl_stmt|;
name|cv
operator|.
name|isRepeating
operator|=
literal|true
expr_stmt|;
name|cv
operator|.
name|noNulls
operator|=
literal|true
expr_stmt|;
name|cv
operator|.
name|vector
index|[
literal|0
index|]
operator|=
name|longValue
expr_stmt|;
block|}
specifier|private
name|void
name|evaluateDouble
parameter_list|(
name|VectorizedRowBatch
name|vrg
parameter_list|)
block|{
name|DoubleColumnVector
name|cv
init|=
operator|(
name|DoubleColumnVector
operator|)
name|vrg
operator|.
name|cols
index|[
name|outputColumn
index|]
decl_stmt|;
name|cv
operator|.
name|isRepeating
operator|=
literal|true
expr_stmt|;
name|cv
operator|.
name|noNulls
operator|=
literal|true
expr_stmt|;
name|cv
operator|.
name|vector
index|[
literal|0
index|]
operator|=
name|doubleValue
expr_stmt|;
block|}
specifier|private
name|void
name|evaluateBytes
parameter_list|(
name|VectorizedRowBatch
name|vrg
parameter_list|)
block|{
name|BytesColumnVector
name|cv
init|=
operator|(
name|BytesColumnVector
operator|)
name|vrg
operator|.
name|cols
index|[
name|outputColumn
index|]
decl_stmt|;
name|cv
operator|.
name|isRepeating
operator|=
literal|true
expr_stmt|;
name|cv
operator|.
name|noNulls
operator|=
literal|true
expr_stmt|;
name|cv
operator|.
name|setRef
argument_list|(
literal|0
argument_list|,
name|bytesValue
argument_list|,
literal|0
argument_list|,
name|bytesValueLength
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|evaluate
parameter_list|(
name|VectorizedRowBatch
name|vrg
parameter_list|)
block|{
switch|switch
condition|(
name|type
condition|)
block|{
case|case
name|LONG
case|:
name|evaluateLong
argument_list|(
name|vrg
argument_list|)
expr_stmt|;
break|break;
case|case
name|DOUBLE
case|:
name|evaluateDouble
argument_list|(
name|vrg
argument_list|)
expr_stmt|;
break|break;
case|case
name|BYTES
case|:
name|evaluateBytes
argument_list|(
name|vrg
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
annotation|@
name|Override
specifier|public
name|int
name|getOutputColumn
parameter_list|()
block|{
return|return
name|outputColumn
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getOutputType
parameter_list|()
block|{
return|return
name|getTypeString
argument_list|()
return|;
block|}
specifier|public
name|long
name|getLongValue
parameter_list|()
block|{
return|return
name|longValue
return|;
block|}
specifier|public
name|void
name|setLongValue
parameter_list|(
name|long
name|longValue
parameter_list|)
block|{
name|this
operator|.
name|longValue
operator|=
name|longValue
expr_stmt|;
block|}
specifier|public
name|double
name|getDoubleValue
parameter_list|()
block|{
return|return
name|doubleValue
return|;
block|}
specifier|public
name|void
name|setDoubleValue
parameter_list|(
name|double
name|doubleValue
parameter_list|)
block|{
name|this
operator|.
name|doubleValue
operator|=
name|doubleValue
expr_stmt|;
block|}
specifier|public
name|byte
index|[]
name|getBytesValue
parameter_list|()
block|{
return|return
name|bytesValue
return|;
block|}
specifier|public
name|void
name|setBytesValue
parameter_list|(
name|byte
index|[]
name|bytesValue
parameter_list|)
block|{
name|this
operator|.
name|bytesValue
operator|=
name|bytesValue
expr_stmt|;
name|this
operator|.
name|bytesValueLength
operator|=
name|bytesValue
operator|.
name|length
expr_stmt|;
block|}
specifier|public
name|String
name|getTypeString
parameter_list|()
block|{
return|return
name|typeString
return|;
block|}
specifier|public
name|void
name|setTypeString
parameter_list|(
name|String
name|typeString
parameter_list|)
block|{
name|this
operator|.
name|typeString
operator|=
name|typeString
expr_stmt|;
if|if
condition|(
literal|"string"
operator|.
name|equalsIgnoreCase
argument_list|(
name|typeString
argument_list|)
condition|)
block|{
name|this
operator|.
name|type
operator|=
name|Type
operator|.
name|BYTES
expr_stmt|;
block|}
elseif|else
if|if
condition|(
literal|"double"
operator|.
name|equalsIgnoreCase
argument_list|(
name|typeString
argument_list|)
condition|)
block|{
name|this
operator|.
name|type
operator|=
name|Type
operator|.
name|DOUBLE
expr_stmt|;
block|}
else|else
block|{
name|this
operator|.
name|type
operator|=
name|Type
operator|.
name|LONG
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|setOutputColumn
parameter_list|(
name|int
name|outputColumn
parameter_list|)
block|{
name|this
operator|.
name|outputColumn
operator|=
name|outputColumn
expr_stmt|;
block|}
block|}
end_class

end_unit

