begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hive
operator|.
name|service
operator|.
name|auth
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|naming
operator|.
name|NamingException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|sasl
operator|.
name|AuthenticationException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|conf
operator|.
name|HiveConf
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hive
operator|.
name|service
operator|.
name|auth
operator|.
name|ldap
operator|.
name|DirSearch
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hive
operator|.
name|service
operator|.
name|auth
operator|.
name|ldap
operator|.
name|DirSearchFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hive
operator|.
name|service
operator|.
name|auth
operator|.
name|ldap
operator|.
name|LdapSearchFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Rule
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|rules
operator|.
name|ExpectedException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|runner
operator|.
name|RunWith
import|;
end_import

begin_import
import|import
name|org
operator|.
name|mockito
operator|.
name|Mock
import|;
end_import

begin_import
import|import
name|org
operator|.
name|mockito
operator|.
name|runners
operator|.
name|MockitoJUnitRunner
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|*
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|*
import|;
end_import

begin_class
annotation|@
name|RunWith
argument_list|(
name|MockitoJUnitRunner
operator|.
name|class
argument_list|)
specifier|public
class|class
name|TestLdapAuthenticationProviderImpl
block|{
annotation|@
name|Rule
specifier|public
name|ExpectedException
name|thrown
init|=
name|ExpectedException
operator|.
name|none
argument_list|()
decl_stmt|;
specifier|public
name|HiveConf
name|conf
decl_stmt|;
specifier|public
name|LdapAuthenticationProviderImpl
name|auth
decl_stmt|;
annotation|@
name|Mock
specifier|public
name|DirSearchFactory
name|factory
decl_stmt|;
annotation|@
name|Mock
specifier|public
name|DirSearch
name|search
decl_stmt|;
annotation|@
name|Before
specifier|public
name|void
name|setup
parameter_list|()
throws|throws
name|AuthenticationException
block|{
name|conf
operator|=
operator|new
name|HiveConf
argument_list|()
expr_stmt|;
name|conf
operator|.
name|set
argument_list|(
literal|"hive.root.logger"
argument_list|,
literal|"DEBUG,console"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|set
argument_list|(
literal|"hive.server2.authentication.ldap.url"
argument_list|,
literal|"localhost"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|factory
operator|.
name|getInstance
argument_list|(
name|any
argument_list|(
name|HiveConf
operator|.
name|class
argument_list|)
argument_list|,
name|anyString
argument_list|()
argument_list|,
name|anyString
argument_list|()
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|search
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|authenticateGivenBlankPassword
parameter_list|()
throws|throws
name|Exception
block|{
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
operator|new
name|LdapSearchFactory
argument_list|()
argument_list|)
expr_stmt|;
name|expectAuthenticationExceptionForInvalidPassword
argument_list|()
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user"
argument_list|,
literal|""
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|authenticateGivenStringWithNullCharacterForPassword
parameter_list|()
throws|throws
name|Exception
block|{
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
operator|new
name|LdapSearchFactory
argument_list|()
argument_list|)
expr_stmt|;
name|expectAuthenticationExceptionForInvalidPassword
argument_list|()
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user"
argument_list|,
literal|"\0"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|authenticateGivenNullForPassword
parameter_list|()
throws|throws
name|Exception
block|{
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
operator|new
name|LdapSearchFactory
argument_list|()
argument_list|)
expr_stmt|;
name|expectAuthenticationExceptionForInvalidPassword
argument_list|()
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user"
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateNoUserOrGroupFilter
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERDNPATTERN
argument_list|,
literal|"cn=%s,ou=Users,dc=mycorp,dc=com:cn=%s,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|DirSearchFactory
name|factory
init|=
name|mock
argument_list|(
name|DirSearchFactory
operator|.
name|class
argument_list|)
decl_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|factory
operator|.
name|getInstance
argument_list|(
name|conf
argument_list|,
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|,
literal|"Blah"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|search
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|factory
operator|.
name|getInstance
argument_list|(
name|conf
argument_list|,
literal|"cn=user1,ou=Users,dc=mycorp,dc=com"
argument_list|,
literal|"Blah"
argument_list|)
argument_list|)
operator|.
name|thenThrow
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user1"
argument_list|,
literal|"Blah"
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|factory
argument_list|,
name|times
argument_list|(
literal|2
argument_list|)
argument_list|)
operator|.
name|getInstance
argument_list|(
name|isA
argument_list|(
name|HiveConf
operator|.
name|class
argument_list|)
argument_list|,
name|anyString
argument_list|()
argument_list|,
name|eq
argument_list|(
literal|"Blah"
argument_list|)
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|atLeastOnce
argument_list|()
argument_list|)
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1,user2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user2"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user2"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenLoginWithDomainAndUserFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1@mydomain.com"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenLoginWithDnAndUserFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserSearchFails
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1,user2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserFilterFails
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1,user2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user3"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user3,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user3"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenGroupMembershipKeyFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"group1,group2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user2"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupsForUser
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=testGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|,
literal|"cn=group1,ou=Groups,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupsForUser
argument_list|(
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=testGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|,
literal|"cn=group2,ou=Groups,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user2"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserAndGroupMembershipKeyFiltersPass
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"group1,group2"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1,user2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user2"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupsForUser
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=testGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|,
literal|"cn=group1,ou=Groups,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupsForUser
argument_list|(
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=testGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|,
literal|"cn=group2,ou=Groups,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1"
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user2"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserFilterPassesAndGroupMembershipKeyFilterFails
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"group1,group2"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1,user2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupsForUser
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=testGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|,
literal|"cn=OtherGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserFilterFailsAndGroupMembershipKeyFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"group3"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user1,user2"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user3"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user3,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupsForUser
argument_list|(
literal|"cn=user3,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=testGroup,ou=Groups,dc=mycorp,dc=com"
argument_list|,
literal|"cn=group3,ou=Groups,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user3"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenCustomQueryFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_BASEDN
argument_list|,
literal|"dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_CUSTOMLDAPQUERY
argument_list|,
literal|"(&(objectClass=person)(|(memberOf=CN=Domain Admins,CN=Users,DC=apache,DC=org)(memberOf=CN=Administrators,CN=Builtin,DC=apache,DC=org)))"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|executeCustomQuery
argument_list|(
name|anyString
argument_list|()
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|,
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user1"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenCustomQueryFilterFailsAndUserFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_BASEDN
argument_list|,
literal|"dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_CUSTOMLDAPQUERY
argument_list|,
literal|"(&(objectClass=person)(|(memberOf=CN=Domain Admins,CN=Users,DC=apache,DC=org)(memberOf=CN=Administrators,CN=Builtin,DC=apache,DC=org)))"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERFILTER
argument_list|,
literal|"user3"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user3"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user3,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|executeCustomQuery
argument_list|(
name|anyString
argument_list|()
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|,
literal|"cn=user2,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
argument_list|)
expr_stmt|;
name|authenticateUserAndCheckSearchIsClosed
argument_list|(
literal|"user3"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserMembershipKeyFilterPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"HIVE-USERS"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_BASEDN
argument_list|,
literal|"dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERMEMBERSHIP_KEY
argument_list|,
literal|"memberOf"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|String
name|groupDn
init|=
literal|"cn=HIVE-USERS,ou=Groups,dc=mycorp,dc=com"
decl_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupDn
argument_list|(
literal|"HIVE-USERS"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|groupDn
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|isUserMemberOfGroup
argument_list|(
literal|"user1"
argument_list|,
name|groupDn
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user1"
argument_list|,
literal|"Blah"
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|factory
argument_list|,
name|times
argument_list|(
literal|1
argument_list|)
argument_list|)
operator|.
name|getInstance
argument_list|(
name|isA
argument_list|(
name|HiveConf
operator|.
name|class
argument_list|)
argument_list|,
name|anyString
argument_list|()
argument_list|,
name|eq
argument_list|(
literal|"Blah"
argument_list|)
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|times
argument_list|(
literal|1
argument_list|)
argument_list|)
operator|.
name|findGroupDn
argument_list|(
name|anyString
argument_list|()
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|times
argument_list|(
literal|1
argument_list|)
argument_list|)
operator|.
name|isUserMemberOfGroup
argument_list|(
name|anyString
argument_list|()
argument_list|,
name|anyString
argument_list|()
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|atLeastOnce
argument_list|()
argument_list|)
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserMembershipKeyFilterFails
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"HIVE-USERS"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_BASEDN
argument_list|,
literal|"dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERMEMBERSHIP_KEY
argument_list|,
literal|"memberOf"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|String
name|groupDn
init|=
literal|"cn=HIVE-USERS,ou=Groups,dc=mycorp,dc=com"
decl_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupDn
argument_list|(
literal|"HIVE-USERS"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|groupDn
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|isUserMemberOfGroup
argument_list|(
literal|"user1"
argument_list|,
name|groupDn
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user1"
argument_list|,
literal|"Blah"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAuthenticateWhenUserMembershipKeyFilter2x2PatternsPasses
parameter_list|()
throws|throws
name|NamingException
throws|,
name|AuthenticationException
throws|,
name|IOException
block|{
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPFILTER
argument_list|,
literal|"HIVE-USERS1,HIVE-USERS2"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_GROUPDNPATTERN
argument_list|,
literal|"cn=%s,ou=Groups,ou=branch1,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERDNPATTERN
argument_list|,
literal|"cn=%s,ou=Userss,ou=branch1,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|conf
operator|.
name|setVar
argument_list|(
name|HiveConf
operator|.
name|ConfVars
operator|.
name|HIVE_SERVER2_PLAIN_LDAP_USERMEMBERSHIP_KEY
argument_list|,
literal|"memberOf"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findUserDn
argument_list|(
literal|"user1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=user1,ou=PowerUsers,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupDn
argument_list|(
literal|"HIVE-USERS1"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=HIVE-USERS1,ou=Groups,ou=branch1,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|findGroupDn
argument_list|(
literal|"HIVE-USERS2"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|"cn=HIVE-USERS2,ou=Groups,ou=branch1,dc=mycorp,dc=com"
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|isUserMemberOfGroup
argument_list|(
literal|"user1"
argument_list|,
literal|"cn=HIVE-USERS1,ou=Groups,ou=branch1,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenThrow
argument_list|(
name|NamingException
operator|.
name|class
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|search
operator|.
name|isUserMemberOfGroup
argument_list|(
literal|"user1"
argument_list|,
literal|"cn=HIVE-USERS2,ou=Groups,ou=branch1,dc=mycorp,dc=com"
argument_list|)
argument_list|)
operator|.
name|thenReturn
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|auth
operator|.
name|Authenticate
argument_list|(
literal|"user1"
argument_list|,
literal|"Blah"
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|factory
argument_list|,
name|times
argument_list|(
literal|1
argument_list|)
argument_list|)
operator|.
name|getInstance
argument_list|(
name|isA
argument_list|(
name|HiveConf
operator|.
name|class
argument_list|)
argument_list|,
name|anyString
argument_list|()
argument_list|,
name|eq
argument_list|(
literal|"Blah"
argument_list|)
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|times
argument_list|(
literal|2
argument_list|)
argument_list|)
operator|.
name|findGroupDn
argument_list|(
name|anyString
argument_list|()
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|times
argument_list|(
literal|2
argument_list|)
argument_list|)
operator|.
name|isUserMemberOfGroup
argument_list|(
name|anyString
argument_list|()
argument_list|,
name|anyString
argument_list|()
argument_list|)
expr_stmt|;
name|verify
argument_list|(
name|search
argument_list|,
name|atLeastOnce
argument_list|()
argument_list|)
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|expectAuthenticationExceptionForInvalidPassword
parameter_list|()
block|{
name|thrown
operator|.
name|expect
argument_list|(
name|AuthenticationException
operator|.
name|class
argument_list|)
expr_stmt|;
name|thrown
operator|.
name|expectMessage
argument_list|(
literal|"a null or blank password has been provided"
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|authenticateUserAndCheckSearchIsClosed
parameter_list|(
name|String
name|user
parameter_list|)
throws|throws
name|IOException
block|{
name|auth
operator|=
operator|new
name|LdapAuthenticationProviderImpl
argument_list|(
name|conf
argument_list|,
name|factory
argument_list|)
expr_stmt|;
try|try
block|{
name|auth
operator|.
name|Authenticate
argument_list|(
name|user
argument_list|,
literal|"password doesn't matter"
argument_list|)
expr_stmt|;
block|}
finally|finally
block|{
name|verify
argument_list|(
name|search
argument_list|,
name|atLeastOnce
argument_list|()
argument_list|)
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

