begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|druid
operator|.
name|serde
package|;
end_package

begin_import
import|import
name|io
operator|.
name|druid
operator|.
name|java
operator|.
name|util
operator|.
name|common
operator|.
name|granularity
operator|.
name|PeriodGranularity
import|;
end_import

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|core
operator|.
name|JsonGenerator
import|;
end_import

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|core
operator|.
name|JsonProcessingException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|databind
operator|.
name|JsonSerializer
import|;
end_import

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|databind
operator|.
name|SerializerProvider
import|;
end_import

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|databind
operator|.
name|jsontype
operator|.
name|TypeSerializer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|joda
operator|.
name|time
operator|.
name|DateTimeZone
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_class
specifier|public
class|class
name|PeriodGranularitySerializer
extends|extends
name|JsonSerializer
argument_list|<
name|PeriodGranularity
argument_list|>
block|{
annotation|@
name|Override
specifier|public
name|void
name|serialize
parameter_list|(
name|PeriodGranularity
name|granularity
parameter_list|,
name|JsonGenerator
name|jsonGenerator
parameter_list|,
name|SerializerProvider
name|serializerProvider
parameter_list|)
throws|throws
name|IOException
throws|,
name|JsonProcessingException
block|{
comment|// Set timezone based on user timezone if origin is not already set
comment|// as it is default Hive time semantics to consider user timezone.
name|PeriodGranularity
name|granularityWithUserTimezone
init|=
operator|new
name|PeriodGranularity
argument_list|(
name|granularity
operator|.
name|getPeriod
argument_list|()
argument_list|,
name|granularity
operator|.
name|getOrigin
argument_list|()
argument_list|,
name|DateTimeZone
operator|.
name|getDefault
argument_list|()
argument_list|)
decl_stmt|;
name|granularityWithUserTimezone
operator|.
name|serialize
argument_list|(
name|jsonGenerator
argument_list|,
name|serializerProvider
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|serializeWithType
parameter_list|(
name|PeriodGranularity
name|value
parameter_list|,
name|JsonGenerator
name|gen
parameter_list|,
name|SerializerProvider
name|serializers
parameter_list|,
name|TypeSerializer
name|typeSer
parameter_list|)
throws|throws
name|IOException
block|{
name|serialize
argument_list|(
name|value
argument_list|,
name|gen
argument_list|,
name|serializers
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

