begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|udf
operator|.
name|generic
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|plan
operator|.
name|ExprNodeConstantDesc
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|udf
operator|.
name|generic
operator|.
name|GenericUDF
operator|.
name|DeferredJavaObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|ql
operator|.
name|udf
operator|.
name|generic
operator|.
name|GenericUDF
operator|.
name|DeferredObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|ObjectInspector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|PrimitiveObjectInspector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|objectinspector
operator|.
name|primitive
operator|.
name|PrimitiveObjectInspectorFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|typeinfo
operator|.
name|TypeInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|typeinfo
operator|.
name|TypeInfoFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|IntWritable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|TestGenericUDFMacro
block|{
specifier|private
name|String
name|name
decl_stmt|;
specifier|private
name|GenericUDFMacro
name|udf
decl_stmt|;
specifier|private
name|List
argument_list|<
name|String
argument_list|>
name|colNames
decl_stmt|;
specifier|private
name|List
argument_list|<
name|TypeInfo
argument_list|>
name|colTypes
decl_stmt|;
specifier|private
name|ObjectInspector
index|[]
name|inspectors
decl_stmt|;
specifier|private
name|DeferredObject
index|[]
name|arguments
decl_stmt|;
specifier|private
name|IntWritable
name|x
decl_stmt|;
specifier|private
name|IntWritable
name|y
decl_stmt|;
specifier|private
name|ExprNodeConstantDesc
name|bodyDesc
decl_stmt|;
specifier|private
name|int
name|expected
decl_stmt|;
annotation|@
name|Before
specifier|public
name|void
name|setup
parameter_list|()
throws|throws
name|Exception
block|{
name|name
operator|=
literal|"fixed_number"
expr_stmt|;
name|colNames
operator|=
operator|new
name|ArrayList
argument_list|<
name|String
argument_list|>
argument_list|()
expr_stmt|;
name|colTypes
operator|=
operator|new
name|ArrayList
argument_list|<
name|TypeInfo
argument_list|>
argument_list|()
expr_stmt|;
name|colNames
operator|.
name|add
argument_list|(
literal|"x"
argument_list|)
expr_stmt|;
name|colTypes
operator|.
name|add
argument_list|(
name|TypeInfoFactory
operator|.
name|intTypeInfo
argument_list|)
expr_stmt|;
name|colNames
operator|.
name|add
argument_list|(
literal|"y"
argument_list|)
expr_stmt|;
name|colTypes
operator|.
name|add
argument_list|(
name|TypeInfoFactory
operator|.
name|intTypeInfo
argument_list|)
expr_stmt|;
name|x
operator|=
operator|new
name|IntWritable
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|y
operator|=
operator|new
name|IntWritable
argument_list|(
literal|2
argument_list|)
expr_stmt|;
name|expected
operator|=
name|x
operator|.
name|get
argument_list|()
operator|+
name|y
operator|.
name|get
argument_list|()
expr_stmt|;
name|bodyDesc
operator|=
operator|new
name|ExprNodeConstantDesc
argument_list|(
name|expected
argument_list|)
expr_stmt|;
name|inspectors
operator|=
operator|new
name|ObjectInspector
index|[]
block|{
name|PrimitiveObjectInspectorFactory
operator|.
name|getPrimitiveWritableConstantObjectInspector
argument_list|(
name|TypeInfoFactory
operator|.
name|intTypeInfo
argument_list|,
name|x
argument_list|)
block|,
name|PrimitiveObjectInspectorFactory
operator|.
name|getPrimitiveWritableConstantObjectInspector
argument_list|(
name|TypeInfoFactory
operator|.
name|intTypeInfo
argument_list|,
name|y
argument_list|)
block|,     }
expr_stmt|;
name|arguments
operator|=
operator|new
name|DeferredObject
index|[]
block|{
operator|new
name|DeferredJavaObject
argument_list|(
name|x
argument_list|)
block|,
operator|new
name|DeferredJavaObject
argument_list|(
name|y
argument_list|)
block|}
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testUDF
parameter_list|()
throws|throws
name|Exception
block|{
name|udf
operator|=
operator|new
name|GenericUDFMacro
argument_list|(
name|name
argument_list|,
name|bodyDesc
argument_list|,
name|colNames
argument_list|,
name|colTypes
argument_list|)
expr_stmt|;
name|udf
operator|.
name|initialize
argument_list|(
name|inspectors
argument_list|)
expr_stmt|;
name|Object
name|actual
init|=
name|udf
operator|.
name|evaluate
argument_list|(
name|arguments
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|bodyDesc
operator|.
name|getValue
argument_list|()
argument_list|,
operator|(
operator|(
name|IntWritable
operator|)
name|actual
operator|)
operator|.
name|get
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|udf
operator|.
name|isDeterministic
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|udf
operator|.
name|isStateful
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|name
argument_list|,
name|udf
operator|.
name|getMacroName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|bodyDesc
argument_list|,
name|udf
operator|.
name|getBody
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|colNames
argument_list|,
name|udf
operator|.
name|getColNames
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|colTypes
argument_list|,
name|udf
operator|.
name|getColTypes
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|name
operator|+
literal|"(x, y)"
argument_list|,
name|udf
operator|.
name|getDisplayString
argument_list|(
operator|new
name|String
index|[]
block|{
literal|"x"
block|,
literal|"y"
block|}
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testNoArgsContructor
parameter_list|()
throws|throws
name|Exception
block|{
name|udf
operator|=
operator|new
name|GenericUDFMacro
argument_list|()
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|udf
operator|.
name|isDeterministic
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|udf
operator|.
name|isStateful
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

