begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/* Generated By:JJTree: Do not edit this line. Node.java */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hive
operator|.
name|serde2
operator|.
name|dynamic_type
package|;
end_package

begin_comment
comment|/* All AST nodes must implement this interface.  It provides basic  machinery for constructing the parent and child relationships  between nodes. */
end_comment

begin_interface
specifier|public
interface|interface
name|Node
block|{
comment|/**    * This method is called after the node has been made the current node. It    * indicates that child nodes can now be added to it.    */
specifier|public
name|void
name|jjtOpen
parameter_list|()
function_decl|;
comment|/**    * This method is called after all the child nodes have been added.    */
specifier|public
name|void
name|jjtClose
parameter_list|()
function_decl|;
comment|/**    * This pair of methods are used to inform the node of its parent.    */
specifier|public
name|void
name|jjtSetParent
parameter_list|(
name|Node
name|n
parameter_list|)
function_decl|;
specifier|public
name|Node
name|jjtGetParent
parameter_list|()
function_decl|;
comment|/**    * This method tells the node to add its argument to the node's list of    * children.    */
specifier|public
name|void
name|jjtAddChild
parameter_list|(
name|Node
name|n
parameter_list|,
name|int
name|i
parameter_list|)
function_decl|;
comment|/**    * This method returns a child node. The children are numbered from zero, left    * to right.    */
specifier|public
name|Node
name|jjtGetChild
parameter_list|(
name|int
name|i
parameter_list|)
function_decl|;
comment|/** Return the number of children the node has. */
specifier|public
name|int
name|jjtGetNumChildren
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

